"""
Scientifically Traceable Component Map Generation Engine.

Produces 2D component maps (emission lines, PAHs, continuum, integrated bands,
uncertainties, SNR, DQ/coverage products) from validated SpectralCube objects
using physical wavelength bin integration (Δλ) and local linear continuum fitting.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
from astropy.io import fits
from astropy.wcs import WCS

from src.core.cube import SpectralCube
from src.imaging.recipes import ContinuumSubtraction, ImageRecipe, RGBChannel


class ComponentMapError(ValueError):
    """Base class for component map generation errors."""


class WavelengthCoverageError(ComponentMapError):
    """Raised when requested feature or continuum bands are outside cube coverage."""


@dataclass
class ComponentMap:
    """Structured, scientifically traceable 2D component map product."""

    data: np.ndarray
    uncertainty: np.ndarray | None
    snr: np.ndarray | None
    dq: np.ndarray | None
    coverage: np.ndarray
    wcs: WCS
    unit: str
    component_name: str
    recipe_channel: str | None
    on_band_flux: np.ndarray
    continuum_map: np.ndarray
    has_authoritative_uncertainty: bool
    provenance: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        """Return JSON-serializable dictionary summary of map product."""
        return {
            "component_name": self.component_name,
            "recipe_channel": self.recipe_channel,
            "unit": self.unit,
            "shape": list(self.data.shape),
            "has_authoritative_uncertainty": self.has_authoritative_uncertainty,
            "valid_spaxel_count": int(np.count_nonzero(np.isfinite(self.data))),
            "provenance": self.provenance,
        }

    def save_fits(self, filepath: str | Path, export_sidecar: bool = True) -> Path:
        """Export component map product as multi-extension FITS with WCS and JSON provenance."""
        dest_path = Path(filepath)
        dest_path.parent.mkdir(parents=True, exist_ok=True)

        header = fits.Header()
        header["COMPONENT"] = self.component_name
        if self.recipe_channel:
            header["CHANNEL"] = self.recipe_channel
        header["BUNIT"] = self.unit
        header["AUTH_ERR"] = self.has_authoritative_uncertainty
        header["COMMENT"] = "JWST MIRI IFU Component Map generated by Phase 5 engine."

        # Add 2D celestial WCS keywords
        if self.wcs is not None:
            wcs_2d = self.wcs.celestial if hasattr(self.wcs, "celestial") else self.wcs
            for k, v in wcs_2d.to_header().items():
                header[k] = v

        primary_hdu = fits.PrimaryHDU(header=header)
        hdus = [primary_hdu]

        # Extension 1: SCI (Continuum-subtracted or integrated flux)
        sci_hdu = fits.ImageHDU(data=self.data.astype(np.float32), header=header, name="SCI")
        hdus.append(sci_hdu)

        # Extension 2: ERR (Uncertainty map)
        if self.uncertainty is not None:
            err_hdu = fits.ImageHDU(data=self.uncertainty.astype(np.float32), header=header, name="ERR")
            hdus.append(err_hdu)

        # Extension 3: SNR
        if self.snr is not None:
            snr_hdu = fits.ImageHDU(data=self.snr.astype(np.float32), header=header, name="SNR")
            hdus.append(snr_hdu)

        # Extension 4: DQ
        if self.dq is not None:
            dq_hdu = fits.ImageHDU(data=self.dq.astype(np.int32), header=header, name="DQ")
            hdus.append(dq_hdu)

        # Extension 5: COV (Coverage count)
        cov_hdu = fits.ImageHDU(data=self.coverage.astype(np.int32), header=header, name="COV")
        hdus.append(cov_hdu)

        # Extension 6: ONBAND
        onband_hdu = fits.ImageHDU(data=self.on_band_flux.astype(np.float32), header=header, name="ONBAND")
        hdus.append(onband_hdu)

        # Extension 7: CONTINUUM
        cont_hdu = fits.ImageHDU(data=self.continuum_map.astype(np.float32), header=header, name="CONTINUUM")
        hdus.append(cont_hdu)

        hdulist = fits.HDUList(hdus)
        hdulist.writeto(dest_path, overwrite=True)

        if export_sidecar:
            sidecar_path = dest_path.with_name(f"{dest_path.name}.provenance.json")
            sidecar_path.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")

        return dest_path


def compute_bin_widths(wavelengths: np.ndarray) -> np.ndarray:
    """Calculate exact physical bin widths Δλ for an array of wavelengths."""
    n = len(wavelengths)
    if n == 1:
        return np.array([0.001], dtype=float)

    delta_wl = np.zeros(n, dtype=float)
    delta_wl[0] = wavelengths[1] - wavelengths[0]
    delta_wl[-1] = wavelengths[-1] - wavelengths[-2]
    delta_wl[1:-1] = (wavelengths[2:] - wavelengths[:-2]) / 2.0
    return delta_wl


def extract_component_map(
    cube: SpectralCube,
    central_wavelength_um: float,
    integration_width_um: float,
    *,
    feature_name: str = "feature",
    continuum_subtraction: ContinuumSubtraction | dict[str, Any] | bool | None = None,
    allow_one_sided_continuum: bool = False,
    recipe_channel: str | None = None,
) -> ComponentMap:
    """Extract a scientifically traceable continuum-subtracted component map.

    Parameters
    ----------
    cube : SpectralCube
        Input validated SpectralCube.
    central_wavelength_um : float
        Target central wavelength in µm.
    integration_width_um : float
        Full width of the on-band feature window in µm.
    feature_name : str
        Name of the spectral feature (e.g. '[Ne II]', 'H2_S1', 'PAH_11.3').
    continuum_subtraction : ContinuumSubtraction, dict, bool, optional
        Continuum subtraction settings.
    allow_one_sided_continuum : bool
        Permit one-sided continuum fallback if one window is off detector edge.
    recipe_channel : str, optional
        RGB display channel identifier ('red', 'green', 'blue').

    Returns
    -------
    ComponentMap
        Structured 2D component map product with uncertainty, SNR, DQ, and provenance.
    """
    wl_min, wl_max = cube.wavelength_range
    on_start = central_wavelength_um - integration_width_um / 2.0
    on_end = central_wavelength_um + integration_width_um / 2.0

    # Validate feature on-band coverage
    if on_start < wl_min or on_end > wl_max:
        raise WavelengthCoverageError(
            f"Feature '{feature_name}' on-band [{on_start:.4f}, {on_end:.4f}] µm is outside "
            f"cube wavelength range [{wl_min:.4f}, {wl_max:.4f}] µm."
        )

    wavelengths = cube.wavelength
    bin_widths = compute_bin_widths(wavelengths)

    on_indices = np.where((wavelengths >= on_start) & (wavelengths <= on_end))[0]
    if len(on_indices) == 0:
        raise WavelengthCoverageError(f"No channels found in on-band [{on_start:.4f}, {on_end:.4f}] µm.")

    on_wl = wavelengths[on_indices]
    on_dwl = bin_widths[on_indices]
    on_dwl_total = np.sum(on_dwl)

    # Parse continuum subtraction configuration
    cont_enabled = False
    sideband_width = integration_width_um
    gap_um = integration_width_um * 0.5
    cont_method = "adjacent_sidebands"

    if isinstance(continuum_subtraction, ContinuumSubtraction):
        cont_enabled = continuum_subtraction.enabled
        if cont_enabled:
            sideband_width = continuum_subtraction.sideband_width_um or sideband_width
            gap_um = continuum_subtraction.gap_um or gap_um
            cont_method = continuum_subtraction.method or cont_method
    elif isinstance(continuum_subtraction, dict):
        cont_enabled = bool(continuum_subtraction.get("enabled", False))
        if cont_enabled:
            sideband_width = continuum_subtraction.get("sideband_width_um") or sideband_width
            gap_um = continuum_subtraction.get("gap_um") or gap_um
            cont_method = continuum_subtraction.get("method") or cont_method
    elif isinstance(continuum_subtraction, bool):
        cont_enabled = continuum_subtraction

    blue_indices: np.ndarray = np.array([], dtype=int)
    red_indices: np.ndarray = np.array([], dtype=int)

    if cont_enabled:
        blue_start = central_wavelength_um - gap_um - sideband_width
        blue_end = central_wavelength_um - gap_um
        red_start = central_wavelength_um + gap_um
        red_end = central_wavelength_um + gap_um + sideband_width

        blue_valid = (blue_start >= wl_min) and (blue_end <= wl_max)
        red_valid = (red_start >= wl_min) and (red_end <= wl_max)

        if not (blue_valid and red_valid):
            if not allow_one_sided_continuum:
                raise WavelengthCoverageError(
                    f"Continuum windows [{blue_start:.4f}, {blue_end:.4f}] and/or [{red_start:.4f}, {red_end:.4f}] µm "
                    f"extend outside cube wavelength range [{wl_min:.4f}, {wl_max:.4f}] µm."
                )
            if not (blue_valid or red_valid):
                raise WavelengthCoverageError(
                    f"Both continuum windows for '{feature_name}' fall outside cube wavelength coverage."
                )

        if blue_valid:
            blue_indices = np.where((wavelengths >= blue_start) & (wavelengths <= blue_end))[0]
        if red_valid:
            red_indices = np.where((wavelengths >= red_start) & (wavelengths <= red_end))[0]

    # Perform physical integration for on-band
    cube_data = cube.data
    cube_err = cube.standard_deviation() if cube.has_err else None
    cube_dq = cube.dq

    ny, nx = cube.spatial_shape

    on_band_flux = np.zeros((ny, nx), dtype=float)
    on_band_var = np.zeros((ny, nx), dtype=float) if cube_err is not None else None
    on_valid = np.zeros((ny, nx), dtype=bool)
    on_cov = np.zeros((ny, nx), dtype=int)

    used_channels = list(on_indices)

    # Accumulate on-band
    for k in on_indices:
        slice_k = cube_data[k]
        dwl_k = bin_widths[k]
        valid_k = np.isfinite(slice_k)

        on_band_flux[valid_k] += slice_k[valid_k] * dwl_k
        on_cov[valid_k] += 1
        on_valid |= valid_k

        if cube_err is not None and on_band_var is not None:
            err_k = cube_err[k]
            on_band_var[valid_k] += (err_k[valid_k] * dwl_k) ** 2

    on_band_flux[~on_valid] = np.nan
    if on_band_var is not None:
        on_band_var[~on_valid] = np.nan

    # Estimate Continuum Map
    continuum_map = np.zeros((ny, nx), dtype=float)
    continuum_var = np.zeros((ny, nx), dtype=float) if cube_err is not None else None

    if cont_enabled and (len(blue_indices) > 0 or len(red_indices) > 0):
        used_channels.extend(blue_indices)
        used_channels.extend(red_indices)

        # Helper to compute mean intensity and variance in a window
        def _window_mean(indices: np.ndarray) -> tuple[np.ndarray, np.ndarray | None, float]:
            if len(indices) == 0:
                return np.zeros((ny, nx)), None, central_wavelength_um

            dwl_win = bin_widths[indices]
            dwl_tot = np.sum(dwl_win)
            wl_mid = float(np.sum(wavelengths[indices] * dwl_win) / dwl_tot)

            flux_sum = np.zeros((ny, nx), dtype=float)
            var_sum = np.zeros((ny, nx), dtype=float) if cube_err is not None else None
            valid_win = np.zeros((ny, nx), dtype=bool)

            for idx in indices:
                sl = cube_data[idx]
                dw = bin_widths[idx]
                v = np.isfinite(sl)
                flux_sum[v] += sl[v] * dw
                valid_win |= v
                if cube_err is not None and var_sum is not None:
                    er = cube_err[idx]
                    var_sum[v] += (er[v] * dw) ** 2

            mean_int = flux_sum / dwl_tot
            mean_var = (var_sum / (dwl_tot**2)) if var_sum is not None else None
            mean_int[~valid_win] = np.nan
            if mean_var is not None:
                mean_var[~valid_win] = np.nan
            return mean_int, mean_var, wl_mid

        blue_mean, blue_var, blue_wl = _window_mean(blue_indices)
        red_mean, red_var, red_wl = _window_mean(red_indices)

        if len(blue_indices) > 0 and len(red_indices) > 0:
            denom = red_wl - blue_wl
            if abs(denom) > 1e-6:
                c_blue = (red_wl - central_wavelength_um) / denom
                c_red = (central_wavelength_um - blue_wl) / denom
            else:
                c_blue, c_red = 0.5, 0.5

            cont_intensity = c_blue * blue_mean + c_red * red_mean
            if cube_err is not None and blue_var is not None and red_var is not None and continuum_var is not None:
                cont_intensity_var = (c_blue**2) * blue_var + (c_red**2) * red_var
                continuum_var = cont_intensity_var * (on_dwl_total**2)
        elif len(blue_indices) > 0:
            cont_intensity = blue_mean
            if cube_err is not None and blue_var is not None and continuum_var is not None:
                continuum_var = blue_var * (on_dwl_total**2)
        else:
            cont_intensity = red_mean
            if cube_err is not None and red_var is not None and continuum_var is not None:
                continuum_var = red_var * (on_dwl_total**2)

        continuum_map = cont_intensity * on_dwl_total

    # Final Subtracted Flux & Uncertainty
    subtracted_data = on_band_flux - continuum_map

    if cube_err is not None and on_band_var is not None:
        total_var = on_band_var + (continuum_var if continuum_var is not None else 0.0)
        uncertainty_map = np.sqrt(np.maximum(0.0, total_var))
        snr_map = np.where((uncertainty_map > 0) & np.isfinite(subtracted_data), subtracted_data / uncertainty_map, np.nan)
        has_auth_err = True
    else:
        uncertainty_map = None
        snr_map = None
        has_auth_err = False

    # DQ Propagation (bitwise OR across all used channels)
    if cube_dq is not None:
        dq_dtype = cube_dq.dtype
        combined_dq = np.zeros((ny, nx), dtype=dq_dtype)
        for k in used_channels:
            combined_dq |= cube_dq[k]
    else:
        combined_dq = None

    # Determine Physical Unit
    base_unit = cube.flux_unit or "MJy/sr"
    unit_str = f"{base_unit} * um" if "um" not in base_unit else base_unit

    # Construct WCS
    wcs_2d = cube.wcs.celestial if cube.wcs is not None else WCS(cube.header).celestial

    provenance = {
        "action": "extract_component_map",
        "component_name": feature_name,
        "recipe_channel": recipe_channel,
        "central_wavelength_um": central_wavelength_um,
        "integration_width_um": integration_width_um,
        "continuum_subtraction_enabled": cont_enabled,
        "continuum_method": cont_method,
        "sideband_width_um": sideband_width,
        "gap_um": gap_um,
        "on_band_channels": len(on_indices),
        "blue_continuum_channels": len(blue_indices),
        "red_continuum_channels": len(red_indices),
        "unit": unit_str,
        "has_authoritative_uncertainty": has_auth_err,
        "source_filepath": str(cube.filepath),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    return ComponentMap(
        data=subtracted_data,
        uncertainty=uncertainty_map,
        snr=snr_map,
        dq=combined_dq,
        coverage=on_cov,
        wcs=wcs_2d,
        unit=unit_str,
        component_name=feature_name,
        recipe_channel=recipe_channel,
        on_band_flux=on_band_flux,
        continuum_map=continuum_map,
        has_authoritative_uncertainty=has_auth_err,
        provenance=provenance,
    )


def extract_recipe_component_maps(
    cube: SpectralCube,
    recipe: ImageRecipe,
    *,
    allow_one_sided_continuum: bool = False,
) -> dict[str, ComponentMap]:
    """Extract component maps for all 3 RGB channels defined in an ImageRecipe.

    Parameters
    ----------
    cube : SpectralCube
        Input validated SpectralCube.
    recipe : ImageRecipe
        Phase 1 RGB Image Recipe.
    allow_one_sided_continuum : bool
        Permit one-sided continuum fallback if one window is off detector edge.

    Returns
    -------
    dict of str -> ComponentMap
        Keys: 'red', 'green', 'blue'.
    """
    maps = {}
    for channel in recipe.channels:
        cmap = extract_component_map(
            cube,
            central_wavelength_um=channel.central_wavelength_um,
            integration_width_um=channel.integration_width_um,
            feature_name=channel.feature_name,
            continuum_subtraction=channel.continuum_subtraction,
            allow_one_sided_continuum=allow_one_sided_continuum,
            recipe_channel=channel.display_colour,
        )
        maps[channel.display_colour] = cmap
    return maps
